defaultIndent: "    "

modifyLineBreaks:
  preserveBlankLines: 1
  condenseMultipleBlankLinesInto: 1
  textWrapOptions:
    columns: 120
    multipleSpacesToSingle: 1

onlyOneBackUp: 1

verbatimEnvironments:
  verbatim: 1
  lstlisting: 1
  minted: 1

noIndentBlock:
  noindent: 1
  cmhtest: 1

lookForAlignDelims:
  tabular: 1
  tabularx: 1
  align: 1
  align*: 1
  equation: 0
  cases: 1
